#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLShop_QA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QlShop_QA")]
	public partial class QLShop_QADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertchatLieu(chatLieu instance);
    partial void UpdatechatLieu(chatLieu instance);
    partial void DeletechatLieu(chatLieu instance);
    partial void Insertquyen(quyen instance);
    partial void Updatequyen(quyen instance);
    partial void Deletequyen(quyen instance);
    partial void InsertchiTietHDBan(chiTietHDBan instance);
    partial void UpdatechiTietHDBan(chiTietHDBan instance);
    partial void DeletechiTietHDBan(chiTietHDBan instance);
    partial void Inserthang(hang instance);
    partial void Updatehang(hang instance);
    partial void Deletehang(hang instance);
    partial void InsertHDBan(HDBan instance);
    partial void UpdateHDBan(HDBan instance);
    partial void DeleteHDBan(HDBan instance);
    partial void Insertkhach(khach instance);
    partial void Updatekhach(khach instance);
    partial void Deletekhach(khach instance);
    partial void InsertnhanVien(nhanVien instance);
    partial void UpdatenhanVien(nhanVien instance);
    partial void DeletenhanVien(nhanVien instance);
    #endregion
		
		public QLShop_QADataContext() : 
				base(global::QLShop_QA.Properties.Settings.Default.QlShop_QAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLShop_QADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLShop_QADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLShop_QADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLShop_QADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chatLieu> chatLieus
		{
			get
			{
				return this.GetTable<chatLieu>();
			}
		}
		
		public System.Data.Linq.Table<quyen> quyens
		{
			get
			{
				return this.GetTable<quyen>();
			}
		}
		
		public System.Data.Linq.Table<chiTietHDBan> chiTietHDBans
		{
			get
			{
				return this.GetTable<chiTietHDBan>();
			}
		}
		
		public System.Data.Linq.Table<hang> hangs
		{
			get
			{
				return this.GetTable<hang>();
			}
		}
		
		public System.Data.Linq.Table<HDBan> HDBans
		{
			get
			{
				return this.GetTable<HDBan>();
			}
		}
		
		public System.Data.Linq.Table<khach> khaches
		{
			get
			{
				return this.GetTable<khach>();
			}
		}
		
		public System.Data.Linq.Table<nhanVien> nhanViens
		{
			get
			{
				return this.GetTable<nhanVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chatLieu")]
	public partial class chatLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maChatLieu;
		
		private string _tenChatLieu;
		
		private EntitySet<hang> _hangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChatLieuChanging(string value);
    partial void OnmaChatLieuChanged();
    partial void OntenChatLieuChanging(string value);
    partial void OntenChatLieuChanged();
    #endregion
		
		public chatLieu()
		{
			this._hangs = new EntitySet<hang>(new Action<hang>(this.attach_hangs), new Action<hang>(this.detach_hangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChatLieu", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maChatLieu
		{
			get
			{
				return this._maChatLieu;
			}
			set
			{
				if ((this._maChatLieu != value))
				{
					this.OnmaChatLieuChanging(value);
					this.SendPropertyChanging();
					this._maChatLieu = value;
					this.SendPropertyChanged("maChatLieu");
					this.OnmaChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenChatLieu", DbType="NVarChar(30)")]
		public string tenChatLieu
		{
			get
			{
				return this._tenChatLieu;
			}
			set
			{
				if ((this._tenChatLieu != value))
				{
					this.OntenChatLieuChanging(value);
					this.SendPropertyChanging();
					this._tenChatLieu = value;
					this.SendPropertyChanged("tenChatLieu");
					this.OntenChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chatLieu_hang", Storage="_hangs", ThisKey="maChatLieu", OtherKey="maChatLieu")]
		public EntitySet<hang> hangs
		{
			get
			{
				return this._hangs;
			}
			set
			{
				this._hangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hangs(hang entity)
		{
			this.SendPropertyChanging();
			entity.chatLieu = this;
		}
		
		private void detach_hangs(hang entity)
		{
			this.SendPropertyChanging();
			entity.chatLieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.quyen")]
	public partial class quyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<nhanVien> _nhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public quyen()
		{
			this._nhanViens = new EntitySet<nhanVien>(new Action<nhanVien>(this.attach_nhanViens), new Action<nhanVien>(this.detach_nhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="quyen_nhanVien", Storage="_nhanViens", ThisKey="id", OtherKey="idQuyen")]
		public EntitySet<nhanVien> nhanViens
		{
			get
			{
				return this._nhanViens;
			}
			set
			{
				this._nhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhanViens(nhanVien entity)
		{
			this.SendPropertyChanging();
			entity.quyen = this;
		}
		
		private void detach_nhanViens(nhanVien entity)
		{
			this.SendPropertyChanging();
			entity.quyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiTietHDBan")]
	public partial class chiTietHDBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHDBan;
		
		private string _maHang;
		
		private System.Nullable<double> _soLuong;
		
		private System.Nullable<double> _donGia;
		
		private System.Nullable<double> _giamGia;
		
		private System.Nullable<double> _thanhTien;
		
		private EntityRef<hang> _hang;
		
		private EntityRef<HDBan> _HDBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDBanChanging(string value);
    partial void OnmaHDBanChanged();
    partial void OnmaHangChanging(string value);
    partial void OnmaHangChanged();
    partial void OnsoLuongChanging(System.Nullable<double> value);
    partial void OnsoLuongChanged();
    partial void OndonGiaChanging(System.Nullable<double> value);
    partial void OndonGiaChanged();
    partial void OngiamGiaChanging(System.Nullable<double> value);
    partial void OngiamGiaChanged();
    partial void OnthanhTienChanging(System.Nullable<double> value);
    partial void OnthanhTienChanged();
    #endregion
		
		public chiTietHDBan()
		{
			this._hang = default(EntityRef<hang>);
			this._HDBan = default(EntityRef<HDBan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHDBan", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHDBan
		{
			get
			{
				return this._maHDBan;
			}
			set
			{
				if ((this._maHDBan != value))
				{
					if (this._HDBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHDBanChanging(value);
					this.SendPropertyChanging();
					this._maHDBan = value;
					this.SendPropertyChanged("maHDBan");
					this.OnmaHDBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHang", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHang
		{
			get
			{
				return this._maHang;
			}
			set
			{
				if ((this._maHang != value))
				{
					if (this._hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHangChanging(value);
					this.SendPropertyChanging();
					this._maHang = value;
					this.SendPropertyChanged("maHang");
					this.OnmaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Float")]
		public System.Nullable<double> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Float")]
		public System.Nullable<double> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giamGia", DbType="Float")]
		public System.Nullable<double> giamGia
		{
			get
			{
				return this._giamGia;
			}
			set
			{
				if ((this._giamGia != value))
				{
					this.OngiamGiaChanging(value);
					this.SendPropertyChanging();
					this._giamGia = value;
					this.SendPropertyChanged("giamGia");
					this.OngiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTien", DbType="Float")]
		public System.Nullable<double> thanhTien
		{
			get
			{
				return this._thanhTien;
			}
			set
			{
				if ((this._thanhTien != value))
				{
					this.OnthanhTienChanging(value);
					this.SendPropertyChanging();
					this._thanhTien = value;
					this.SendPropertyChanged("thanhTien");
					this.OnthanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hang_chiTietHDBan", Storage="_hang", ThisKey="maHang", OtherKey="maHang", IsForeignKey=true)]
		public hang hang
		{
			get
			{
				return this._hang.Entity;
			}
			set
			{
				hang previousValue = this._hang.Entity;
				if (((previousValue != value) 
							|| (this._hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hang.Entity = null;
						previousValue.chiTietHDBans.Remove(this);
					}
					this._hang.Entity = value;
					if ((value != null))
					{
						value.chiTietHDBans.Add(this);
						this._maHang = value.maHang;
					}
					else
					{
						this._maHang = default(string);
					}
					this.SendPropertyChanged("hang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HDBan_chiTietHDBan", Storage="_HDBan", ThisKey="maHDBan", OtherKey="maHDBan", IsForeignKey=true)]
		public HDBan HDBan
		{
			get
			{
				return this._HDBan.Entity;
			}
			set
			{
				HDBan previousValue = this._HDBan.Entity;
				if (((previousValue != value) 
							|| (this._HDBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HDBan.Entity = null;
						previousValue.chiTietHDBans.Remove(this);
					}
					this._HDBan.Entity = value;
					if ((value != null))
					{
						value.chiTietHDBans.Add(this);
						this._maHDBan = value.maHDBan;
					}
					else
					{
						this._maHDBan = default(string);
					}
					this.SendPropertyChanged("HDBan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hang")]
	public partial class hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHang;
		
		private string _tenHang;
		
		private string _maChatLieu;
		
		private System.Nullable<double> _soLuong;
		
		private System.Nullable<double> _donGiaNhap;
		
		private System.Nullable<double> _donGiaBan;
		
		private string _anh;
		
		private string _ghiChu;
		
		private EntitySet<chiTietHDBan> _chiTietHDBans;
		
		private EntityRef<chatLieu> _chatLieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHangChanging(string value);
    partial void OnmaHangChanged();
    partial void OntenHangChanging(string value);
    partial void OntenHangChanged();
    partial void OnmaChatLieuChanging(string value);
    partial void OnmaChatLieuChanged();
    partial void OnsoLuongChanging(System.Nullable<double> value);
    partial void OnsoLuongChanged();
    partial void OndonGiaNhapChanging(System.Nullable<double> value);
    partial void OndonGiaNhapChanged();
    partial void OndonGiaBanChanging(System.Nullable<double> value);
    partial void OndonGiaBanChanged();
    partial void OnanhChanging(string value);
    partial void OnanhChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public hang()
		{
			this._chiTietHDBans = new EntitySet<chiTietHDBan>(new Action<chiTietHDBan>(this.attach_chiTietHDBans), new Action<chiTietHDBan>(this.detach_chiTietHDBans));
			this._chatLieu = default(EntityRef<chatLieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHang", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHang
		{
			get
			{
				return this._maHang;
			}
			set
			{
				if ((this._maHang != value))
				{
					this.OnmaHangChanging(value);
					this.SendPropertyChanging();
					this._maHang = value;
					this.SendPropertyChanged("maHang");
					this.OnmaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenHang", DbType="NVarChar(30)")]
		public string tenHang
		{
			get
			{
				return this._tenHang;
			}
			set
			{
				if ((this._tenHang != value))
				{
					this.OntenHangChanging(value);
					this.SendPropertyChanging();
					this._tenHang = value;
					this.SendPropertyChanged("tenHang");
					this.OntenHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChatLieu", DbType="NVarChar(10)")]
		public string maChatLieu
		{
			get
			{
				return this._maChatLieu;
			}
			set
			{
				if ((this._maChatLieu != value))
				{
					if (this._chatLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaChatLieuChanging(value);
					this.SendPropertyChanging();
					this._maChatLieu = value;
					this.SendPropertyChanged("maChatLieu");
					this.OnmaChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Float")]
		public System.Nullable<double> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGiaNhap", DbType="Float")]
		public System.Nullable<double> donGiaNhap
		{
			get
			{
				return this._donGiaNhap;
			}
			set
			{
				if ((this._donGiaNhap != value))
				{
					this.OndonGiaNhapChanging(value);
					this.SendPropertyChanging();
					this._donGiaNhap = value;
					this.SendPropertyChanged("donGiaNhap");
					this.OndonGiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGiaBan", DbType="Float")]
		public System.Nullable<double> donGiaBan
		{
			get
			{
				return this._donGiaBan;
			}
			set
			{
				if ((this._donGiaBan != value))
				{
					this.OndonGiaBanChanging(value);
					this.SendPropertyChanging();
					this._donGiaBan = value;
					this.SendPropertyChanged("donGiaBan");
					this.OndonGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh", DbType="NVarChar(200)")]
		public string anh
		{
			get
			{
				return this._anh;
			}
			set
			{
				if ((this._anh != value))
				{
					this.OnanhChanging(value);
					this.SendPropertyChanging();
					this._anh = value;
					this.SendPropertyChanged("anh");
					this.OnanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(200)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hang_chiTietHDBan", Storage="_chiTietHDBans", ThisKey="maHang", OtherKey="maHang")]
		public EntitySet<chiTietHDBan> chiTietHDBans
		{
			get
			{
				return this._chiTietHDBans;
			}
			set
			{
				this._chiTietHDBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chatLieu_hang", Storage="_chatLieu", ThisKey="maChatLieu", OtherKey="maChatLieu", IsForeignKey=true)]
		public chatLieu chatLieu
		{
			get
			{
				return this._chatLieu.Entity;
			}
			set
			{
				chatLieu previousValue = this._chatLieu.Entity;
				if (((previousValue != value) 
							|| (this._chatLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chatLieu.Entity = null;
						previousValue.hangs.Remove(this);
					}
					this._chatLieu.Entity = value;
					if ((value != null))
					{
						value.hangs.Add(this);
						this._maChatLieu = value.maChatLieu;
					}
					else
					{
						this._maChatLieu = default(string);
					}
					this.SendPropertyChanged("chatLieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chiTietHDBans(chiTietHDBan entity)
		{
			this.SendPropertyChanging();
			entity.hang = this;
		}
		
		private void detach_chiTietHDBans(chiTietHDBan entity)
		{
			this.SendPropertyChanging();
			entity.hang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HDBan")]
	public partial class HDBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHDBan;
		
		private string _maNhanVien;
		
		private System.Nullable<System.DateTime> _ngayBan;
		
		private string _maKhach;
		
		private System.Nullable<double> _tongTien;
		
		private EntitySet<chiTietHDBan> _chiTietHDBans;
		
		private EntityRef<khach> _khach;
		
		private EntityRef<nhanVien> _nhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDBanChanging(string value);
    partial void OnmaHDBanChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OnngayBanChanging(System.Nullable<System.DateTime> value);
    partial void OnngayBanChanged();
    partial void OnmaKhachChanging(string value);
    partial void OnmaKhachChanged();
    partial void OntongTienChanging(System.Nullable<double> value);
    partial void OntongTienChanged();
    #endregion
		
		public HDBan()
		{
			this._chiTietHDBans = new EntitySet<chiTietHDBan>(new Action<chiTietHDBan>(this.attach_chiTietHDBans), new Action<chiTietHDBan>(this.detach_chiTietHDBans));
			this._khach = default(EntityRef<khach>);
			this._nhanVien = default(EntityRef<nhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHDBan", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHDBan
		{
			get
			{
				return this._maHDBan;
			}
			set
			{
				if ((this._maHDBan != value))
				{
					this.OnmaHDBanChanging(value);
					this.SendPropertyChanging();
					this._maHDBan = value;
					this.SendPropertyChanged("maHDBan");
					this.OnmaHDBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(10)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._nhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayBan", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayBan
		{
			get
			{
				return this._ngayBan;
			}
			set
			{
				if ((this._ngayBan != value))
				{
					this.OnngayBanChanging(value);
					this.SendPropertyChanging();
					this._ngayBan = value;
					this.SendPropertyChanged("ngayBan");
					this.OnngayBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhach", DbType="NVarChar(10)")]
		public string maKhach
		{
			get
			{
				return this._maKhach;
			}
			set
			{
				if ((this._maKhach != value))
				{
					if (this._khach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhachChanging(value);
					this.SendPropertyChanging();
					this._maKhach = value;
					this.SendPropertyChanged("maKhach");
					this.OnmaKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTien", DbType="Float")]
		public System.Nullable<double> tongTien
		{
			get
			{
				return this._tongTien;
			}
			set
			{
				if ((this._tongTien != value))
				{
					this.OntongTienChanging(value);
					this.SendPropertyChanging();
					this._tongTien = value;
					this.SendPropertyChanged("tongTien");
					this.OntongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HDBan_chiTietHDBan", Storage="_chiTietHDBans", ThisKey="maHDBan", OtherKey="maHDBan")]
		public EntitySet<chiTietHDBan> chiTietHDBans
		{
			get
			{
				return this._chiTietHDBans;
			}
			set
			{
				this._chiTietHDBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khach_HDBan", Storage="_khach", ThisKey="maKhach", OtherKey="makhach", IsForeignKey=true)]
		public khach khach
		{
			get
			{
				return this._khach.Entity;
			}
			set
			{
				khach previousValue = this._khach.Entity;
				if (((previousValue != value) 
							|| (this._khach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khach.Entity = null;
						previousValue.HDBans.Remove(this);
					}
					this._khach.Entity = value;
					if ((value != null))
					{
						value.HDBans.Add(this);
						this._maKhach = value.makhach;
					}
					else
					{
						this._maKhach = default(string);
					}
					this.SendPropertyChanged("khach");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_HDBan", Storage="_nhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public nhanVien nhanVien
		{
			get
			{
				return this._nhanVien.Entity;
			}
			set
			{
				nhanVien previousValue = this._nhanVien.Entity;
				if (((previousValue != value) 
							|| (this._nhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanVien.Entity = null;
						previousValue.HDBans.Remove(this);
					}
					this._nhanVien.Entity = value;
					if ((value != null))
					{
						value.HDBans.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("nhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chiTietHDBans(chiTietHDBan entity)
		{
			this.SendPropertyChanging();
			entity.HDBan = this;
		}
		
		private void detach_chiTietHDBans(chiTietHDBan entity)
		{
			this.SendPropertyChanging();
			entity.HDBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khach")]
	public partial class khach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makhach;
		
		private string _tenkhach;
		
		private string _gioiTinh;
		
		private string _diachi;
		
		private string _dienthoai;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private EntitySet<HDBan> _HDBans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhachChanging(string value);
    partial void OnmakhachChanged();
    partial void OntenkhachChanging(string value);
    partial void OntenkhachChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    #endregion
		
		public khach()
		{
			this._HDBans = new EntitySet<HDBan>(new Action<HDBan>(this.attach_HDBans), new Action<HDBan>(this.detach_HDBans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhach", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makhach
		{
			get
			{
				return this._makhach;
			}
			set
			{
				if ((this._makhach != value))
				{
					this.OnmakhachChanging(value);
					this.SendPropertyChanging();
					this._makhach = value;
					this.SendPropertyChanged("makhach");
					this.OnmakhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhach", DbType="NVarChar(30)")]
		public string tenkhach
		{
			get
			{
				return this._tenkhach;
			}
			set
			{
				if ((this._tenkhach != value))
				{
					this.OntenkhachChanging(value);
					this.SendPropertyChanging();
					this._tenkhach = value;
					this.SendPropertyChanged("tenkhach");
					this.OntenkhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(10)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(30)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="NVarChar(15)")]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khach_HDBan", Storage="_HDBans", ThisKey="makhach", OtherKey="maKhach")]
		public EntitySet<HDBan> HDBans
		{
			get
			{
				return this._HDBans;
			}
			set
			{
				this._HDBans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HDBans(HDBan entity)
		{
			this.SendPropertyChanging();
			entity.khach = this;
		}
		
		private void detach_HDBans(HDBan entity)
		{
			this.SendPropertyChanging();
			entity.khach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanVien")]
	public partial class nhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNhanVien;
		
		private string _tenNhanVien;
		
		private string _gioiTinh;
		
		private string _diaChi;
		
		private string _dienThoai;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _taikhoan;
		
		private string _matkhau;
		
		private System.Nullable<int> _idQuyen;
		
		private EntitySet<HDBan> _HDBans;
		
		private EntityRef<quyen> _quyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OntenNhanVienChanging(string value);
    partial void OntenNhanVienChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OndienThoaiChanging(string value);
    partial void OndienThoaiChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnidQuyenChanging(System.Nullable<int> value);
    partial void OnidQuyenChanged();
    #endregion
		
		public nhanVien()
		{
			this._HDBans = new EntitySet<HDBan>(new Action<HDBan>(this.attach_HDBans), new Action<HDBan>(this.detach_HDBans));
			this._quyen = default(EntityRef<quyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanVien", DbType="NVarChar(30)")]
		public string tenNhanVien
		{
			get
			{
				return this._tenNhanVien;
			}
			set
			{
				if ((this._tenNhanVien != value))
				{
					this.OntenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._tenNhanVien = value;
					this.SendPropertyChanged("tenNhanVien");
					this.OntenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(10)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(30)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienThoai", DbType="NVarChar(15)")]
		public string dienThoai
		{
			get
			{
				return this._dienThoai;
			}
			set
			{
				if ((this._dienThoai != value))
				{
					this.OndienThoaiChanging(value);
					this.SendPropertyChanging();
					this._dienThoai = value;
					this.SendPropertyChanged("dienThoai");
					this.OndienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(100)")]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(100)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idQuyen", DbType="Int")]
		public System.Nullable<int> idQuyen
		{
			get
			{
				return this._idQuyen;
			}
			set
			{
				if ((this._idQuyen != value))
				{
					if (this._quyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidQuyenChanging(value);
					this.SendPropertyChanging();
					this._idQuyen = value;
					this.SendPropertyChanged("idQuyen");
					this.OnidQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_HDBan", Storage="_HDBans", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<HDBan> HDBans
		{
			get
			{
				return this._HDBans;
			}
			set
			{
				this._HDBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="quyen_nhanVien", Storage="_quyen", ThisKey="idQuyen", OtherKey="id", IsForeignKey=true)]
		public quyen quyen
		{
			get
			{
				return this._quyen.Entity;
			}
			set
			{
				quyen previousValue = this._quyen.Entity;
				if (((previousValue != value) 
							|| (this._quyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._quyen.Entity = null;
						previousValue.nhanViens.Remove(this);
					}
					this._quyen.Entity = value;
					if ((value != null))
					{
						value.nhanViens.Add(this);
						this._idQuyen = value.id;
					}
					else
					{
						this._idQuyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("quyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HDBans(HDBan entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = this;
		}
		
		private void detach_HDBans(HDBan entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = null;
		}
	}
}
#pragma warning restore 1591
